version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGODB_ROOT_PASSWORD=1234
      - MONGODB_USERNAME=1234
      - MONGODB_PASSWORD=1234
      - MONGODB_DATABASE=1234
    volumes:
      - 'mongodb_master_data:/bitnami'
    networks:
      - dbnetwork
volumes:
  mongodb_master_data:
    driver: local
networks:
  dbnetwork:
   driver: bridge
